#!/usr/bin/env bash
# Copyright 2024, identinet GmbH. All rights reserved.
# SPDX-License-Identifier: MIT

set -eEuo pipefail

CLUSTER="${cluster_name}"
export KUBECONFIG="${cwd}/.kube/config"

###################

if [ "$(kubectl config current-context)" = "$CLUSTER" ]; then
	kubectl config unset current-context
fi
kubectl config unset "clusters.$CLUSTER"
kubectl config unset "users.$CLUSTER"
kubectl config unset "contexts.$CLUSTER"
