#!/usr/bin/env bash
set -eEuo pipefail

CLUSTER="${cluster_name}"
export KUBECONFIG="${cwd}/.kube/config"

###################

if [ "$(kubectl config current-context)" = "$CLUSTER" ]; then
	kubectl config unset current-context
fi
kubectl config unset "clusters.$CLUSTER"
kubectl config unset "users.$CLUSTER"
kubectl config unset "contexts.$CLUSTER"
